apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: "v1.15.x"
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  targetNamespace: rook-ceph
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      enabled: true
