apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 12h
  values:
    interval: 1m
    logLevel: info
    
    provider: 
      name: webhook
    
    extraArgs:
      - --webhook-provider-url=http://localhost:8888
    
    sidecars:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
        ports:
          - containerPort: 8888
            name: webhook
        env:
          - name: ADGUARD_URL
            value: "http://192.168.1.87:88"
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: adguard-credentials
                key: username
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: adguard-credentials
                key: password
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: SERVER_PORT
            value: "8888"
          - name: DOMAIN_FILTER
            value: "local.claytoncowart.com"
          - name: DRY_RUN
            value: "false"
          - name: LOG_LEVEL
            value: "info"
        livenessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 5
    
    sources:
      - service
      - ingress
    
    domainFilters:
      - local.claytoncowart.com
    
    policy: sync  # or "upsert-only" if you don't want it to delete records
    
    txtOwnerId: "external-dns-k8s"
    txtPrefix: "_external-dns."
