apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "1.15.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  targetNamespace: external-dns
  values:
    provider: # Choose: cloudflare, aws, azure, etc.
    sources:
      - service
      - ingress
    domainFilters:
      - example.com  # Your domain
    policy: sync
    txtOwnerId: talos-cluster
    # Add provider-specific configuration
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: token
