apiVersion: v1
kind: Secret
metadata:
  name: adguard-credentials
  namespace: external-dns
type: Opaque
stringData:
  username: "ccowart"  # Replace with your AdGuard username
  password: "Perlatcho20"  # Replace with your AdGuard password
